name: Build and Deploy

on:
  push:
    branches:
      - main
      - markbangert-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Upload to S3
      run: |
        aws s3 sync * s3://images-4-hdf-website-raw/ --include "**/Kleinwalsertal*.jpg" 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
