name: Build Website

on:
  push:
    branches:
    - main
    - markbangert-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync src s3://images-4-hdf-website-raw --delete --acl public-read --exclude "*" --include "**/Kleinwalsertal*.jpeg"
